### ISSUE TITLE
Expected image resolution

### ISSUE THREAD

**Issue by jspaezp** [simongraham/hovernet_inference#28]
Hello, I had a small question regarding the expected input for the model.

What is the expected resolution for the images, in terms of micrometer/pixel.

Kindest wishes,
Sebastian

**Comment by simongraham** [comment]
Hi @jspaezp ,

The input is at 40x objective magnification, which is around 0.275 microns/pixel. For WSI mode, the top level of the image pyramid is taken (level 0, which is the scan resolution). For ROI mode, please ensure that your supplied images are at an appropriate resolution 👍

**Comment by jspaezp** [comment]
I feel like this would be good to mention in the README !
Thank you very much for the reply!

**Comment by simongraham** [comment]
@jspaezp thanks for the suggestion. We will add that info this week.

**Comment by ciaobladoo** [comment]
Is it possible to use it on slides with scan resolution of 20x (0.5 microns/pixel)?
