### ISSUE TITLE
Time taken to process a RoI

### ISSUE THREAD

**Issue by AshStuff** [simongraham/hovernet_inference#29]
Hello,
I am running inference on a RoI with size 4548×7520. The time taken to finish processing  a single RoI is around 20 minutes. Is it the normal behavior ? I can see that the most of the time taken is from the `process_instance` function in `process_utils.py` The main reason is the number of `pred_id_list` is so huge.

**Comment by simongraham** [comment]
Hi @AshStuff ,

I apologise for the delay in getting back to you here. Yes, dealing with large ROIs can be slow. The post processing can take a long time due to the very large search space for post processing.

**Comment by simongraham** [comment]
We are looking to make some changes this week that should speed up this time.
