### ISSUE TITLE
There is a little typo in the ReadMe file

### ISSUE THREAD

**Issue by zeeshanalipnhwr** [simongraham/hovernet_inference#32]
It should be `.npy` where it is `.npz` written in the [ReadMe.md](https://github.com/simongraham/hovernet_inference/blob/master/README.md#running-the-code) file of this repository.

**Comment by simongraham** [comment]
Hi @zeeshanalipnhwr ,

Thanks for reaching out. This in fact is not a typo. You can see that this is the output file format [here](https://github.com/simongraham/hovernet_inference/blob/master/run.py#L561). The wsi mode will output a `.npz` file. Check out [this](https://numpy.org/doc/stable/reference/generated/numpy.savez.html) for more info.

Note, we are currently incorporating a refactor of the code in the `major_refactor` branch. This will actually then save the results as `.json`.
