### ISSUE TITLE
Pannuke weights?

### ISSUE THREAD

**Issue by cirellic** [simongraham/hovernet_inference#39]
I am interested in using the pannuke weights for a project I am currently working on but they seem to have disappeared from the linked Google Drive Folder. Is there another way I can access said weights? Thank you!

**Comment by simongraham** [comment]
Hi @cirellic , 

I apologise for this - not sure what happened there ! I will sort this out tomorrow.

**Comment by cirellic** [comment]
Thanks for looking into this @simongraham !

**Comment by simongraham** [comment]
@cirellic you will now be able to access the pannuke weights
